update backstage metadata name (#221)
(MINOR) No spaces allowed in metadata name
Fixes:

{"error":{"name":"InputError","message":"InputError: Policy check failed
for component:default/ndc postgres configuration server; caused by
Error: \"metadata.name\" is not valid; expected a string that is
sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63
characters in total but found \"ndc postgres configuration server\". To
learn more about catalog file format, visit:
https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":400}}